---
services:
  garage:
    container_name: garage
    restart: unless-stopped
    image: dxflrs/amd64_garage:v2.0.0
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - ./volumes/garage/meta:/var/lib/garage/meta
      - ./volumes/garage/data:/var/lib/garage/data
    network_mode: host
